server:
    port: 8182

spring:
    application:
        name: resource-service

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: http://localhost:8761/eureka
        instance:
            hostname: localhost
